name: Build

permissions:
  pull-requests: write

on:
  push:
    branches:
      - main
    paths:
      - 'packages/**'
  pull_request:
    paths:
      - 'packages/**'

jobs:
  chroma:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 9
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      - name: Build packages
        run: pnpm run build

      - name: Run Chromatic
        uses: chromaui/action@latest
        with:
          workingDir: packages/celeste-vue
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}

      - name: Report chroma url
        if: github.event_name == 'pull_request'
        uses: thollander/actions-comment-pull-request@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          message: |
            Chromatic preview: ${{ steps.chromatic.outputs.url }}
